### ISSUE TITLE
Camille: what's this file?

### ISSUE THREAD

**Issue by rchikhi** [kamimrcht/REINDEER#3]
https://github.com/kamimrcht/REINDEER/blob/master/test/out_test/out_query_Reindeer0.out
seems to contains a sample output for querying unitigs

```
>0 LN:i:31 KC:i:6130 km:f:6130.0   L:-:0:- L:-:507	6130	4693
>1 LN:i:31 KC:i:11 km:f:11.0   L:-:510:-  L:+:559:	11	4
..
```

whereas when I run the test query from the README (`./Reindeer --query -q test/query_test.fa -l quick_out -o quick_query`), output is about the reads:

```
>SRR10092187.4 HISEQ:815:HK2NNBCXY:1:1101:1131:209      *       *
>SRR10092187.5 HISEQ:815:HK2NNBCXY:1:1101:1242:212      *       *
>SRR10092187.6 HISEQ:815:HK2NNBCXY:1:1101:1224:213      33      2
```

**Comment by kamimrcht** [comment]
Those two files are unrelated.
`./Reindeer --query -q test/query_test.fa -l quick_out -o quick_query` is a **toy example**.
The other file is used to **test REINDEER**, with **test.sh**.

**Comment by rchikhi** [comment]
ah I see, thanks!
