### ISSUE TITLE
Compilation issue 

### ISSUE THREAD

**Issue by SwapnilDoijad** [kamimrcht/REINDEER#30]
$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cmake --version
cmake version 3.20.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ git clone --recursive https://github.com/kamimrcht/REINDEER.git
$ cd REINDEER
$ make
echo "#define VERSION \"1.4.6.rc1-3-g59cdfe2\"" > version.h
g++ -o main.o -c main.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o blight.o -c blight/blight.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o utils_b.o -c blight/utils.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
gcc -o trlec.o -c trle/trlec.c -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing -g -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o trled.o -c trle/trled.c -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing -g -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
g++ -o monotig.o -c src/monotig.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o utils.o -c src/utils.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o reindeer.o -c src/reindeer.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o query.o -c src/query.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o build_index.o -c src/build_index.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o eq_classes.o -c src/eq_classes.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o launch_bcalm.o -c src/launch_bcalm.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o matrix_operation.o -c src/matrix_operation.cpp -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
gcc -o blight/lz4/lz4frame.o -c blight/lz4/lz4frame.c -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing -g -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o blight/lz4/lz4.o -c blight/lz4/lz4.c -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing -g -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o blight/lz4/xxhash.o -c blight/lz4/xxhash.c -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing -g -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o blight/lz4/lz4hc.o -c blight/lz4/lz4hc.c -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing -g -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
g++ -o Reindeer main.o blight.o utils_b.o trlec.o trled.o monotig.o utils.o reindeer.o query.o build_index.o eq_classes.o launch_bcalm.o matrix_operation.o blight/lz4/lz4frame.o blight/lz4/lz4.o blight/lz4/xxhash.o blight/lz4/lz4hc.o -DNDEBUG -Ofast -flto -msse4 -fstrict-aliasing  -g -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
/tmp/ccFa8kbx.ltrans0.ltrans.o: In function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format) [clone .constprop.147]':
/usr/include/c++/8/bits/fs_path.h:185: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/tmp/ccFa8kbx.ltrans0.ltrans.o: In function `std::filesystem::__cxx11::path::path<char [14], std::filesystem::__cxx11::path>(char const (&) [14], std::filesystem::__cxx11::path::format) [clone .constprop.145]':
/usr/include/c++/8/bits/fs_path.h:185: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/tmp/ccFa8kbx.ltrans0.ltrans.o: In function `std::enable_if<std::__and_<std::__not_<std::is_same<std::remove_cv<char [14]>::type, std::filesystem::__cxx11::path> >, std::__not_<std::is_void<std::remove_pointer<char [14]>::type> >, std::filesystem::__cxx11::path::__constructible_from<char [14], void> >::value, std::filesystem::__cxx11::path>::type& std::filesystem::__cxx11::path::operator/=<char [14]>(char const (&) [14]) [clone .constprop.142]':
/usr/include/c++/8/bits/fs_path.h:381: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/include/c++/8/bits/fs_path.h:381: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/include/c++/8/bits/fs_path.h:258: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
/usr/include/c++/8/bits/fs_path.h:261: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/tmp/ccFa8kbx.ltrans1.ltrans.o: In function `Is_Writeable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/c++/8/bits/fs_ops.h:121: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/tmp/ccFa8kbx.ltrans1.ltrans.o: In function `Is_Writeable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/groups/VEO/tools/reindeer/v1.4.6/src/utils.cpp:575: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `std::filesystem::__cxx11::path::operator=(std::filesystem::__cxx11::path&&) [clone .part.76] [clone .lto_priv.194]':
/usr/include/c++/8/bits/fs_path.h:310: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/usr/include/c++/8/bits/fs_ops.h:121: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/home/groups/VEO/tools/reindeer/v1.4.6/main.cpp:255: undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/usr/include/c++/8/bits/fs_path.h:185: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/usr/include/c++/8/bits/fs_ops.h:121: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/home/groups/VEO/tools/reindeer/v1.4.6/main.cpp:291: undefined reference to `std::filesystem::current_path[abi:cxx11]()'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/usr/include/c++/8/bits/fs_ops.h:121: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/home/groups/VEO/tools/reindeer/v1.4.6/main.cpp:325: undefined reference to `std::filesystem::create_directories(std::filesystem::__cxx11::path const&)'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/usr/include/c++/8/bits/fs_path.h:1062: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
/usr/include/c++/8/bits/fs_path.h:178: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/include/c++/8/bits/fs_path.h:546: undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/home/groups/VEO/tools/reindeer/v1.4.6/main.cpp:310: undefined reference to `std::filesystem::__cxx11::path::parent_path() const'
/tmp/ccFa8kbx.ltrans4.ltrans.o: In function `main':
/usr/include/c++/8/bits/fs_path.h:546: undefined reference to `std::filesystem::__cxx11::path::compare(std::filesystem::__cxx11::path const&) const'
collect2: error: ld returned 1 exit status
make: *** [makefile:30: Reindeer] Error 1
$

**Comment by kamimrcht** [comment]
Hi, 

Yes, C++8 is not supported. Please try with C++11 or later versions.

Best.

**Comment by SwapnilDoijad** [comment]
Thanks for the quick response, but I still get 

$ which g++
/cluster/spack/v0.19/opt/spack/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-11.3.0-qiu3osfge5vckyeorfcnv73q66yr5etz/bin/g++

$ g++ --version
g++ (Spack GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ echo $CXX
/cluster/spack/v0.19/opt/spack/linux-almalinux8-x86_64_v3/gcc-8.5.0/gcc-11.3.0-qiu3osfge5vckyeorfcnv73q66yr5etz/bin/g++

$ make DEBUG=1
echo "#define VERSION \"1.4.6.rc1-3-g59cdfe2\"" > version.h
g++ -o main.o -c main.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o blight.o -c blight/blight.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o utils_b.o -c blight/utils.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
gcc -o trlec.o -c trle/trlec.c -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o trled.o -c trle/trled.c -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
g++ -o monotig.o -c src/monotig.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o utils.o -c src/utils.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o reindeer.o -c src/reindeer.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o query.o -c src/query.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o build_index.o -c src/build_index.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o eq_classes.o -c src/eq_classes.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o launch_bcalm.o -c src/launch_bcalm.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o matrix_operation.o -c src/matrix_operation.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
gcc -o blight/lz4/lz4frame.o -c blight/lz4/lz4frame.c -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o blight/lz4/lz4.o -c blight/lz4/lz4.c -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o blight/lz4/xxhash.o -c blight/lz4/xxhash.c -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
gcc -o blight/lz4/lz4hc.o -c blight/lz4/lz4hc.c -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
g++ -o Reindeer main.o blight.o utils_b.o trlec.o trled.o monotig.o utils.o reindeer.o query.o build_index.o eq_classes.o launch_bcalm.o matrix_operation.o blight/lz4/lz4frame.o blight/lz4/lz4.o blight/lz4/xxhash.o blight/lz4/lz4hc.o -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o reindeer_socket.o -c src/reindeer_socket.cpp -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
g++ -o reindeer_socket reindeer_socket.o blight.o utils_b.o trlec.o trled.o utils.o reindeer.o query.o build_index.o eq_classes.o matrix_operation.o blight/lz4/lz4frame.o blight/lz4/lz4.o blight/lz4/xxhash.o blight/lz4/lz4hc.o -O0 -DDEBUGi -fstrict-aliasing -msse4 -g -std=c++17 -pipe -lz -fopenmp -Iblight/lz4 
/usr/bin/ld: Dwarf Error: Can't find .debug_ranges section.
build_index.o: In function `Reindeer_Index<unsigned char>::build_index()':
build_index.cpp:(.text._ZN14Reindeer_IndexIhE11build_indexEv[_ZN14Reindeer_IndexIhE11build_indexEv]+0x54): undefined reference to `set_monotigs_output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
build_index.cpp:(.text._ZN14Reindeer_IndexIhE11build_indexEv[_ZN14Reindeer_IndexIhE11build_indexEv]+0x142): undefined reference to `kmer_Set_Light::construct_index_fof(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
build_index.cpp:(.text._ZN14Reindeer_IndexIhE11build_indexEv[_ZN14Reindeer_IndexIhE11build_indexEv]+0x20b): undefined reference to `kmer_Set_Light::construct_index_fof(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
build_index.o: In function `Reindeer_Index<unsigned short>::build_index()':
build_index.cpp:(.text._ZN14Reindeer_IndexItE11build_indexEv[_ZN14Reindeer_IndexItE11build_indexEv]+0x54): undefined reference to `set_monotigs_output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
build_index.cpp:(.text._ZN14Reindeer_IndexItE11build_indexEv[_ZN14Reindeer_IndexItE11build_indexEv]+0x142): undefined reference to `kmer_Set_Light::construct_index_fof(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
build_index.cpp:(.text._ZN14Reindeer_IndexItE11build_indexEv[_ZN14Reindeer_IndexItE11build_indexEv]+0x20b): undefined reference to `kmer_Set_Light::construct_index_fof(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
make: *** [makefile:87: reindeer_socket] Error 1
$
